// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_ball.cpp"
#include "6YEA5652QU/moc_main_window.cpp"
#include "6YEA5652QU/moc_paddle.cpp"
#include "6YEA5652QU/moc_player.cpp"
#include "6YEA5652QU/moc_scene.cpp"
#include "6YEA5652QU/moc_view.cpp"
